/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Common Crypto
 #	author : miyako
 #	2016/03/31
 #
 # --------------------------------------------------------------------------------*/

#include "openssl/ssl.h"
#include "openssl/bio.h"
#include "openssl/evp.h"
#include "openssl/buffer.h"
#include "openssl/hmac.h"
#include "openssl/pkcs12.h"
#include "openssl/err.h"

// --- Common Crypto
void PEM_From_P12(PA_PluginParameters params);
void Get_timestamp(PA_PluginParameters params);
void Get_timestring(PA_PluginParameters params);
void Get_unixtime(PA_PluginParameters params);
void RSASHA256(PA_PluginParameters params);
void HMACMD5(PA_PluginParameters params);
void HMACSHA1(PA_PluginParameters params);
void HMACSHA256(PA_PluginParameters params);
void HMACSHA384(PA_PluginParameters params);
void HMACSHA512(PA_PluginParameters params);
void SHA384(PA_PluginParameters params);
void SHA512(PA_PluginParameters params);
void MD5(PA_PluginParameters params);
void SHA1(PA_PluginParameters params);
void SHA256(PA_PluginParameters params);
void RSASHA1(PA_PluginParameters params);
void AES128(PA_PluginParameters params);
void AES192(PA_PluginParameters params);
void AES256(PA_PluginParameters params);
void RIPEMD160(PA_PluginParameters params);
void RSAVERIFYSHA1(PA_PluginParameters params);
void RSAVERIFYSHA256(PA_PluginParameters params);

#if VERSIONWIN
FILE _iob[] = { *stdin, *stdout, *stderr };

extern "C" FILE * __cdecl __iob_func(void)
{
	return _iob;
}
#endif
